server:
  port: 9000

spring:
  application:
    name: AuthServer
  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:9000


#logging:
#  level:
#    root: DEBUG
#  file:
#    name: logs/app1.log  # Путь к файлу для записи логов
